name: Atualizacao Diaria do Meta Warzone

on:
  schedule:
    # 03:00 UTC = 00:00 Horário de Brasília
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  sincronizar-meta:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Instalar dependências e navegador Chromium
        run: |
          npm init -y
          npm install puppeteer
          npx puppeteer browsers install chrome

      - name: Executar script de sincronizacao do Meta
        run: node atualizar_meta_local.js

      - name: Salvar alterações no repositório
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          # Verifica se existem alterações para commitar evitando exit code 1
          if git diff --staged --quiet; then
            echo "Nenhuma alteração encontrada para commit."
          else
            git commit -m "chore(meta): atualização automática dos dados de armas [skip ci]"
            git push
          fi